// <auto-generated />
namespace _06_ContraintesRelationsWithAnnotations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class oneToManyAuthorCourse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(oneToManyAuthorCourse));
        
        string IMigrationMetadata.Id
        {
            get { return "202210190816190_oneToManyAuthorCourse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
