// <auto-generated />
namespace _04_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RenameColumnNomToNameInFournisseurClasse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameColumnNomToNameInFournisseurClasse));
        
        string IMigrationMetadata.Id
        {
            get { return "202210181307225_RenameColumnNomToNameInFournisseurClasse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
